server.port: 8082
server.error.include-message: always

spring:
  profiles:
    include: domain
  datasource:
    url: jdbc:mysql://localhost:3306/olmago_product_auth
    username: olmago
    password: olmago
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10

spring.cloud.function:
  definition: functionRouter
  routing-expression: headers['type']

spring.cloud.stream:
  defaultBinder: kafka

  kafka:
    binder:
      brokers: 127.0.0.1
      defaultBrokerPort: 9093
      replication-factor: 1

  default.contentType: application/json

  bindings:
    product-auth-event-0:
      destination: product-auth-event-topic
      producer:
        required-groups: auditGroup

    functionRouter-in-0:
      destination: contract-event-topic
      group: product-auth-group
      consumer:
        maxAttempts: 3
        backOffInitialInterval: 500
        backOffMaxInterval: 1000
        backOffMultiplier: 2.0

logging:
  level:
    root: INFO
    team.caltech.olmago.contract.productauth: INFO
    com:
      querydsl:
        sql: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

---
spring.profiles: docker

server.port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olmago_product_auth