spring.rabbitmq:
  addresses: localhost
  username: user
  password: bitnami

spring.cloud.function:
  definition: functionRouter
  routing-expression: headers['type']

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    functionRouter-in-0:
      destination: contract-event-topic
      group: mygroup
      consumer:
        maxAttempts: 3
        backOffInitialInterval: 500
        backOffMaxInterval: 1000
        backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.functionRouter-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true