server.port: 8082
server.error.include-message: always

logging:
  level:
    root: INFO
    team.caltech.olmago.contract.domain: DEBUG
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: DEBUG

app:
  customer-service:
    host: localhost
    port: 8082