spring:
  profiles:
    include: domain
  datasource:
    url: jdbc:mysql://localhost:3306/olmago_contract
    username: olmago
    password: olmago
    driver-class-name: com.mysql.cj.jdbc.Driver
    #schema: classpath*:db/mysql/schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

spring.rabbitmq:
  addresses: localhost
  username: user
  password: bitnami

spring.cloud.function:
  definition: functionRouter
  routing-expression: headers['type']

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    contract-out-0:
      destination: contract-event-topic
      producer:
        required-groups: auditGroup

    functionRouter-in-0:
      destination: order-command-topic,billing-event-topic,coupon-event-topic,customer-event-topic,product-auth-topic
      group: mygroup
      consumer:
        maxAttempts: 3
        backOffInitialInterval: 500
        backOffMaxInterval: 1000
        backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.functionRouter-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

logging:
  level:
    root: INFO
    team.caltech.olmago.contract.domain: INFO
    com:
      querydsl:
        sql: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
