spring:
  config:
    activate:
      on-profile: kafka-prod

spring.kafka.bootstrap-servers: ${KAFKA_BROKER_SERVER}:${KAFKA_BROKER_IP}

spring.cloud.stream:
  kafka:
    binder:
      brokers: ${KAFKA_BROKER_SERVER}
      defaultBrokerPort: ${KAFKA_BROKER_IP}
      replication-factor: 1