server.port: 8081
server.error.include-message: always

spring:
  profiles:
    include: domain
  datasource:
    url: jdbc:mysql://localhost:3306/olmago_contract
    username: olmago
    password: olmago
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10

#spring.rabbitmq:
#  addresses: localhost
#  username: user
#  password: bitnami

spring.cloud.function:
  definition: functionRouter
  routing-expression: headers['message-name']

spring.kafka.bootstrap-servers: 127.0.0.1:9093

spring.cloud.stream:
  defaultBinder: kafka

  kafka:
    binder:
      brokers: 127.0.0.1
      defaultBrokerPort: 9093
      replication-factor: 1

  default.contentType: application/json

  bindings:
    contract-event-0:
      destination: contract-event-topic
      producer:
        required-groups: auditGroup

    functionRouter-in-0:
      destination: order-command-topic,billing-event-topic,coupon-event-topic,customer-event-topic,product-auth-topic
      group: contract-group
      consumer:
        maxAttempts: 3
        backOffInitialInterval: 500
        backOffMaxInterval: 1000
        backOffMultiplier: 2.0

#spring.cloud.stream.rabbit.bindings.functionRouter-in-0.consumer:
#  autoBindDlq: true
#  republishToDlq: true

logging:
  level:
    root: INFO
    team.caltech.olmago.contract.domain: INFO
    com:
      querydsl:
        sql: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

---
spring.profiles: docker

server.port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olmago_contract